- name: Configure the EC2 instance to run a sample app 
  hosts: _ch2_instances 
  gather_facts: true 
  become: true 
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ./ansible-ch2.key
  roles:
    - sample-app
  
