plugin: amazon.aws.aws_ec2
regions:
  - us-east-2
keyed_groups:
  - key: tags.Ansible
    leading_separator: ''
compose:
  ansible_user: ec2-user
  ansible_ssh_private_key_file: ./ansible-ch2.key
filters:
  "tag:Name": "sample-app-ansible"
